apiVersion: v1
kind: ConfigMap
metadata:
  name: ghost-config
  namespace: ghost
data:
  database__client: mysql
  database__connection__host: mysql
  database__connection__user: ghost
  database__connection__password: ghostpass
  database__connection__database: ghostdb
  url: http://ghost-service
